<center><u><H1>Naive Bayes Classifier</H1></u></center>

In [4]:
import pandas as pd
import numpy as np
from sklearn import datasets
#FUNCION TEOREMA
from sklearn.naive_bayes import GaussianNB
#DIVIDIR LA DATA
from sklearn.model_selection import train_test_split
#METRICAS CLASFICACION
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

from sklearn.model_selection import cross_val_score
%matplotlib inline

In [5]:
#DATA
iris = datasets.load_iris()

In [6]:
#VER LA DATA 5 PRIMERAS FUKS
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [7]:
#ETUQUETAS DE CLASE
iris.target[:5]

array([0, 0, 0, 0, 0])

## Transforming data:

In [11]:
# X=CARACTERISTICAM TODAS LAS FILAS, COLUMNAS 2 Y 3
X = iris.data[:,[2,3]]
Y = iris.target

In [12]:
#DIVIDIR TABLA 30% MUESTREO
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=2019)

In [13]:
#ESCALADO DATA ESTANDARIZAR LOS DATOS EN UNA MISMA ESCALA
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.transform(X_test)

## Creating a model

In [14]:
nb = GaussianNB()

In [16]:
#ENTRENAR
nb.fit(X_train_std, Y_train)

GaussianNB()

## Metrics:

In [17]:
print(f"Accuracy:{accuracy_score(Y_test, nb.predict(X_test_std))}")

Accuracy:0.9777777777777777


In [18]:
print(f"Confusion matrix: \n{confusion_matrix(Y_test, nb.predict(X_test_std))}")

Confusion matrix: 
[[19  0  0]
 [ 0  9  1]
 [ 0  0 16]]


In [19]:
print(f"Classification report:\n{classification_report(Y_test, nb.predict(X_test_std))}")

Classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.90      0.95        10
           2       0.94      1.00      0.97        16

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45



## Cross Validation:

In [20]:
cross_val_score(nb, iris.data, iris.target, scoring="accuracy", cv=10)

array([0.93333333, 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.93333333, 0.86666667, 1.        , 1.        , 1.        ])

In [21]:
cross_val_score(nb, iris.data, iris.target, scoring="accuracy", cv=10).mean()

0.9533333333333334

## Printing Data and Decision Boundaries

In [25]:
import Plotting_Decision_Boundaries as db

<class 'ModuleNotFoundError'>: No module named 'Plotting_Decision_Boundaries'

In [26]:
X_combined_std = np.vstack((X_train_std, X_test_std))
y_combined = np.hstack((Y_train, Y_test))

In [27]:
db.plotting_db(X=X_combined_std, y=y_combined, classifier=nb)

<class 'NameError'>: name 'db' is not defined

## Reference:

http://scikit-learn.org/stable/modules/naive_bayes.html