# Metrics in Classification

In [1]:
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

## Accuracy Score

In [2]:
y_pred = [0, 2, 1, 3]
y_true = [0, 1, 2, 3]
print(f"Accuracy Score: {accuracy_score(y_true, y_pred)}")

Accuracy Score: 0.5


## Confusion Matrix

In [3]:
y_true = [2, 0, 2, 2, 0, 1]
y_pred = [0, 0, 2, 2, 0, 2]
print(f"Confusion Matrix:\n {confusion_matrix(y_true, y_pred)}")

Confusion Matrix:
 [[2 0 0]
 [0 0 1]
 [1 0 2]]


In [4]:
y_true = [2, 0, 2, 2, 0, 1]
y_pred = [0, 0, 2, 2, 0, 2]
print(f"Confusion Matrix:\n {confusion_matrix(y_true, y_pred, labels=[0, 1, 2])}")

Confusion Matrix:
 [[2 0 0]
 [0 0 1]
 [1 0 2]]


In [5]:
y_true = [0, 0, 0, 1, 1, 1, 1, 1]
y_pred = [0, 1, 0, 1, 0, 1, 0, 1]
tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
print(f"True negative: {tn}\nFalse Positive: {fp}\nFalse Negative: {fn}\nTrue Positive: {tp}")

True negative: 2
False Positive: 1
False Negative: 2
True Positive: 3


## Classification Report

In [6]:
y_true = [0, 1, 2, 2, 0]
y_pred = [0, 0, 2, 1, 0]
target_names = ['class 0', 'class 1', 'class 2']
print(f"Classification Report:\n{classification_report(y_true, y_pred, target_names=target_names)}")

Classification Report:
              precision    recall  f1-score   support

     class 0       0.67      1.00      0.80         2
     class 1       0.00      0.00      0.00         1
     class 2       1.00      0.50      0.67         2

    accuracy                           0.60         5
   macro avg       0.56      0.50      0.49         5
weighted avg       0.67      0.60      0.59         5



## Reference:

https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter