<center><u><H1>NUMPY</H1><u></center>   

In [3]:
import numpy as np
#convención np

## Creating an array:

In [4]:
array = np.array([[0,1,2],[3,4,5],[6,7,8]])
#crear un array
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Check the attributes:

In [5]:
array.ndim
#numero de dimensioness

2

In [6]:
array.shape
#Numero de filas y columnas

(3, 3)

In [7]:
array.size
#lenght. cuantos elementos

9

In [8]:
array.dtype.name
#de que tipo son lo datos

'int32'

## Mathematical Operations:

In [9]:
#Substraction.
a = np.array([6,5,4,8])
b = np.array([1,2,5,10])
a-b
#misma estructura de datos

array([ 5,  3, -1, -2])

In [10]:
#Squaring an array (operaciones de potencia)
b**2
#de python

array([  1,   4,  25, 100])

In [11]:
np.square(b)
#de numpy

array([  1,   4,  25, 100])

In [12]:
#Applying trigonometic functions. Operaciones triginométricas
np.sin(b)

array([ 0.84147098,  0.90929743, -0.95892427, -0.54402111])

In [13]:
#Conditional operations. Operaciones condicionales
b>1

array([False,  True,  True,  True])

In [14]:
#Matrix multiplication
#algebra lineal
M1 = np.array([[1,2],[0,1]])
M2 = np.array([[-1,0],[1,1]])
M1*M2

array([[-1,  0],
       [ 0,  1]])

In [15]:
#The dot product o producto punto ??
np.dot(M1,M2)

array([[1, 2],
       [1, 1]])

In [16]:
# non values: valor nulo
arr = np.array([1.5, 0.8, np.nan, 3.5])
arr

array([1.5, 0.8, nan, 3.5])

In [17]:
arr[np.isnan(arr)] = 0
arr
#que los que son nulos los iguale a cero

array([1.5, 0.8, 0. , 3.5])

## Statistical Operations:

In [18]:
list = [1,3,-0.5,7,-3,15.4,8.2,7.5]

In [19]:
array = np.array(list)
#convertir lista en Array. Numpy trabaja básicamente con Array

In [20]:
print('Mean:', array.mean())
print('Median:', np.median(array))
print('Range (Max-Min):', np.ptp(array))
print('Standard deviation:', array.std())
print('80th percentile:', np.percentile(array, 80))
print('0.3-quantile:', np.quantile(array, 0.3))

Mean: 4.825
Median: 5.0
Range (Max-Min): 18.4
Standard deviation: 5.507438152172024
80th percentile: 7.92
0.3-quantile: 1.2000000000000002


## Indexing and slicing:
### Propiedades relativas a la indexación

In [21]:
#Index positions (acceso a los datos)
a = np.array([[3,4,5],[7,8,3],[0,3,23],[8,11,6]])
a[1,1]

8

In [22]:
a[0,0:2]
#fila 0, desde posición 0 al 1 (no se cuenta el ultimo indice 2)

array([3, 4])

In [23]:
a[0,:]
#extraer todas las columnas de la fila

array([3, 4, 5])

In [24]:
a[:,1]
#todas las filas de la columna 1

array([ 4,  8,  3, 11])

In [25]:
a[:,-1]
#todas las filas de la ultima coluna

array([ 5,  3, 23,  6])

## Shape Manipulation:
### Trnasformar estructura de un arreglo

In [26]:
a.ravel()
#cambiar estructura de arreglo 2d en una sola dimensión

array([ 3,  4,  5,  7,  8,  3,  0,  3, 23,  8, 11,  6])

In [27]:
a.shape=(4,3)
a
#arreglo a tupla de 4 filas, 3 columnas

array([[ 3,  4,  5],
       [ 7,  8,  3],
       [ 0,  3, 23],
       [ 8, 11,  6]])

In [28]:
a.transpose()
#se utiliza mucho en algebra lineal es la transpuesta de una matriz? 
#las filas son columnas y viceversa

array([[ 3,  7,  0,  8],
       [ 4,  8,  3, 11],
       [ 5,  3, 23,  6]])

In [29]:
c = np.linspace(-1,1,20)
c
#de -1 a 1 (20 valores)

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

In [30]:
# NEW AXIS
x1 = np.array([1, 2, 3, 4, 5])
x1.shape

(5,)

In [31]:
x1_new = x1[:, np.newaxis]
x1_new
#agregar nuevas dimensiones
#se crea una matrix de 2D

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [32]:
x1_new.shape

(5, 1)

In [33]:
x2 = np.array([6, 7, 8])
x3 = x1_new + x2
x3

array([[ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12],
       [11, 12, 13]])

In [34]:
x3_new = x3[:,np.newaxis,0]
x3_new
#toda la DATA.... con newaxis 2d y extraigo la columna 0

array([[ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [35]:
x3_new_ = x3[:,0]
x3_new_
#no aplico newaxis... una sola dimensión

array([ 7,  8,  9, 10, 11])

In [36]:
# Squeeze
arr = np.array([[[2, 2, 2], [2, 2, 2]]])   
print(arr)
print("Shape of input array : ", arr.shape) 
#creo, imprimo y veo cuantas dimensiones


[[[2 2 2]
  [2 2 2]]]
Shape of input array :  (1, 2, 3)


In [37]:
arr_ = np.squeeze(arr)  
print(arr_)
print("Shape of output array : ", arr_.shape) 
#reduce las dimensiones de 3 a 2

[[2 2 2]
 [2 2 2]]
Shape of output array :  (2, 3)


## Reference:

https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

https://docs.scipy.org